name: Build, Push to Docker Hub & then to ECR

on:
  push:
    branches:
      - main

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}         # Now a secret
  ECR_REPOSITORY: test
  DOCKERHUB_IMAGE_NAME: potluriujwala/awsapp

jobs:
  build-push-sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ env.DOCKERHUB_PASSWORD }}" | docker login -u "${{ env.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ env.DOCKERHUB_IMAGE_NAME }}:${{ github.run_number }} .

      - name: Push Docker image to Docker Hub
        run: docker push ${{ env.DOCKERHUB_IMAGE_NAME }}:${{ github.run_number }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Pull image from Docker Hub
        run: docker pull ${{ env.DOCKERHUB_IMAGE_NAME }}:${{ github.run_number }}

      - name: Tag image for ECR
        run: |
          ECR_IMAGE_NAME=${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}
          docker tag ${{ env.DOCKERHUB_IMAGE_NAME }}:${{ github.run_number }} $ECR_IMAGE_NAME:${{ github.run_number }}

      - name: Push image to ECR
        run: |
          ECR_IMAGE_NAME=${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}
          docker push $ECR_IMAGE_NAME:${{ github.run_number }}
